// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/profBisi/Dropbox/kofo/apps/msuMobile/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/profBisi/Dropbox/kofo/apps/msuMobile/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/Users/profBisi/Dropbox/kofo/apps/msuMobile/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('msuMobile', appParameters);
});